### ISSUE TITLE
The harvest frequency setting is meaningless.

### ISSUE THREAD

**Issue by dassolkim** [ckan/ckanext-harvest#300] opened 2017-10-30 04:50 UTC
I have installed and run the latest version of CKAN.

However, there was a. problem with Harvesting. When I created harvest_source, I set the harvest frequency to daily. I experimented by gather_consumer and fetch_consumer in shell, and running harvester run command in another shell. When the harvester run command is executed, I confirmed that the next_run column is updated in the harvest_source table of the DB. However, the harvester did not work when next_run was run. The reason for setting the harvest_source frequency is for automatic harvesting, but it did not work that way.

Also, If I run reharvest on the web, the job will not end. This is also done by running the harvest run command in shell. I do not know how to solve these problems.

Much grateful for your potential help.

**Comment by metaodi** [comment] 2017-10-30 06:58
The basic idea is this:
* `gather_consumer` and `fetch_consumer` are setup as background tasks, so that the run all the time (e.g. as daemons using systemd or init)
* `run` is setup as cron job to run every 15min or so

With each call to `run` several things are checked:
* check each harvest source and its configured frequency if a new job must be created
* if there is a job to run: run it by invoking it's gather stage (after that, the consumers in the background will take over)
* check if a job has finished, if so mark it as "Finished"

So the `run` command takes care of updating the status and running/creating jobs when necessary.

**Comment by dassolkim** [comment] 2017-10-30 08:31
thank you for response.

I know consumer setup as background tasks.

With `gather_consumer` and `fetch_consumer` running, I set the frequency of harvest_source to daily and experimented.

However, it did not automatically harvest at the time when `next_run` should be executed.
It only worked once when I first ran it.

How can I run automatically harvest job to daily?

**Comment by amercader** [comment] 2017-10-30 10:14
@dassolkim as @metaodi pointed out you need to run 3 things:

* `gather_consumer`
* `fetch_consumer`
* `run` command

The `run` command is the one that computes the frequency based on the source configuration and fires new jobs if needed. If you set it to `daily` and just fire the `run` command manually it won't get marked as finished (so that's why you see the job as not finished in the UI), and won't start the next scheduled job.

You need to run the `run` command periodically and often (eg via a cron job) so the job statuses get updated and the frequency value takes effect.

**Comment by metaodi** [comment] 2018-03-03 07:37
I'm closing this for now. If the issue is still there, feel free to comment to re-open it.

**Closed by metaodi** 2018-03-03 07:37 UTC
Labels: bug
