### ISSUE TITLE
gather_consumer -> gather-consumer; fetch_consumer -> fetch-consumer

### ISSUE THREAD

**Issue by kdwarn** [ckan/ckanext-harvest#428] opened 2020-12-23 12:41 UTC
I'm using the latest version (1.3.2) of this plugin on CKAN 2.9, installed about a week ago. Following along with the instructions (both for manual runs and for setting this up in production), I had to change the command from `fetch_consumer` to `fetch-consumer` and `gather_consumer` to `gather-consumer` in order for them to run (otherwise was getting "no such command" error). I was going to submit a pull request with a change to the documentation to reflect this, but upon looking at the code, it looks like the original commands with the underscores are what the function names are. So I'm not sure where the change from `_` to `-` is taking place, or if perhaps there's something I'm missing about this and the reason I had to do it. I only realized that this was the solution when I ran `ckan harvester --help`, and the commands there (except for `harvesters_info`) are listed with `-` in them rather than `_`. Thoughts?

**Comment by VladimirZD** [comment] 2021-03-19 11:36
Hi, we just had this issue today, i lost about 1 hour before  we found out that gether-consumer is working and gether_consumer isnt...

Any ideas what is the cause of this?

**Comment by seitenbau-govdata** [comment] 2021-03-19 11:55
I think this isn't a issue in the code, because the terms `gather-consumer` and `fetch-consumer` cannot found in the repo by the GitHub search, whereas `gather_consumer` and `fetch_consumer` can found.

Perhaps you want to let us know your environments and show your scripts, so we can maybe see what is different?

**Comment by amercader** [comment] 2021-03-19 12:36
This is annoying. It looks like Click automatically changes underscores to hyphens https://github.com/pallets/click/issues/1123, so even though we define the command with an underscore to keep compatibility that gets ignored:

https://github.com/ckan/ckanext-harvest/blob/6222e38c85f04027f3fd9b2894a9c26ee7bd172f/ckanext/harvest/cli.py#L232

The fix is easy, just explicitly set the name with `@harvester.command("gather_consumer")`, but that would mean that we would break scripts that have used the new version and changed their scripts to `gather-consumer` in the meantime. And to be honest it would go against the convention in CKAN core as well so perhaps is better to bite to bullet and accept the change.

So my slight preference would be to leave things as they are, update the [README](https://github.com/ckan/ckanext-harvest#command-line-interface) and clearly state there that when upgrading to CKAN 2.9 you might need to adjust your scripts.

What do people think?

**Comment by VladimirZD** [comment] 2021-03-19 13:05
Updating README would help a lot, because that is first place ppl will look :).
I was also checking source files but that was after i didn't have any idea why command which worked yesterday don't work today..:)

**Comment by VladimirZD** [comment] 2021-03-19 13:13
To be honest calling harvester command without params  "ckan --config=/etc/ckan/default/ckan.ini harvester"
Shows correct help, but that isn't something we tried first.
I was trying ckan --config=/etc/ckan/default/ckan.ini harvester  --help which doesn't work.. 

It says no such command 'harvester'.
Major issue for me was that yesterday gether_consumer worked, we did colleague said to me that he did upgrade from 2.9 to 2.9.2 and it stopped working..

So it was pretty strange situation :)

**Comment by kdwarn** [comment] 2021-03-19 17:48
I think updating the documentation is a good solution.

**Comment by quinoescobar** [comment] 2021-08-04 13:53
Well after spending like 30 minutes wondering what was the problem with the upgrade I found this issue threat and notice the README info it's not updated.
Updating the documentation will be great.

**Comment by jbrown-xentity** [comment] 2021-08-31 16:16
Agreed. The US data.gov team just spent an hour dealing with these issues as well...

**Comment by metaodi** [comment] 2021-09-01 12:00
I merged #439 and propose #454 to add a specific note about the change to the README.

**Comment by amercader** [comment] 2021-09-01 13:35
Thanks @metaodi ! The docs should be clearer now

**Closed** 2021-09-01 13:34 UTC
