### ISSUE TITLE
Missing 'new' form

### ISSUE THREAD

**Issue by rossjones** [ckan/ckanext-harvest#219] opened 2016-01-14 08:36 UTC
With latest CKAN master, and ckanext-harvest master.

Installed as per instructions and when visiting /harvest all is well, although I have no sources.  If I click add source then the page renders but there is no form in the primary_content block.  

The template exists, and is specified by the IDatasetForm for the harvest dataset type, but it doesn't appear to be rendered.  

Tried with a sysadmin, and a normal organization admin.  Possibly related is that I didn't notice a tab at /organization/edit/test which I thought was how they were managed on an org basis.  When attempting to visit /organization/harvest/test I get the following exception 

```
File '/vagrant/ckanext-harvest/ckanext/harvest/controllers/organization.py', line 10 in <module>
  import ckan.new_authz
ImportError: No module named new_authz
```

**Comment by amercader** [comment] 2016-01-14 10:17
This was indeed caused by https://github.com/ckan/ckan/pull/2818, as we are using `c.form` to render the form. Patch incoming.

**Comment by amercader** [comment] 2016-01-14 12:03
This should now be fixed in master

**Closed by amercader** 2016-01-14 12:03 UTC
Labels: bug

**Comment by benjaminleighton** [comment] 2016-02-04 05:16
I'm still getting this problem in master. Is it merged?

**Comment by amercader** [comment] 2016-02-04 12:51
Doh! Forgot to merge in master. Sorry about that @benjaminleighton could you check now?

**Comment by benjaminleighton** [comment] 2016-02-05 05:46
Thanks, that worked for me.
